package utils

object constants {
  val DANH_GIA_DN_CHAP_HANH_TOT: Int = 1

  val DANH_GIA_DN_KHONG_CHAP_HANH_TOT: Int = 1

  val DANH_GIA_DN_BAO_LANH_THUE: Int = 2

  val DANH_GIA_DN_DUA_HANG_VE_BAO_QUAN: Int = 4

  val DANH_GIA_DN_KTSTQ_THEO_KE_HOACH: Int = 8

  val DANH_GIA_DN_AN_HAN: Int = 16

  val DANH_GIA_DN_XAC_DINH_TRUOC_TRI_GIA: Int = 32

  val DANH_GIA_DN_KIEM_TRA_TRUOC_HOAN_THUE_SAU: Int = 64

  val DANH_GIA_DN_HOAN_THUE_TRUOC_KIEM_TRA_SAU_365_NGAY: Int = 128

  val DANH_GIA_DN_HOAN_THUE_TRUOC_KIEM_TRA_SAU_10_NAM: Int = 256

  val LOAI_PHIEN_BAN_DN_CHAP_HANH_TOT: Int = 1

  val LOAI_PHIEN_BAN_DN_BAO_LANH_THUE: Int = 2

  val LOAI_PHIEN_BAN_DN_DUA_HANG_VE_BAO_QUAN: Int = 3

  val LOAI_PHIEN_BAN_DN_KTSTQ_THEO_KE_HOACH: Int = 4

  val LOAI_PHIEN_BAN_DN_KHONG_CHAP_HANH_TOT: Int = 5

  val LOAI_PHIEN_BAN_DN_AN_HAN: Int = 6

  val LOAI_PHIEN_BAN_DN_XAC_DINH_TRUOC_TRI_GIA: Int = 7

  val LOAI_PHIEN_BAN_DN_KIEM_TRA_TRUOC_HOAN_THUE_SAU: Int = 8

  val LOAI_PHIEN_BAN_DN_HOAN_THUE_TRUOC_KIEM_TRA_SAU_365_NGAY: Int = 9

  val LOAI_PHIEN_BAN_DN_HOAN_THUE_TRUOC_KIEM_TRA_SAU_10_NAM: Int = 10
}
